### ISSUE TITLE
What is a Topanga?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [eagleEggs/topanga#2] opened 2018-09-29 05:35 UTC
And when can I see a screenshot of one?  

I REALLY want to see one now that I've seen some test code with a partial view.  It looks like a GREAT looking GUI!

**Comment by eagleEggs** [comment] 2018-09-29 05:42
Thanks :D I just updated the readme with the latest. So easy with your tool! Love it

**Comment by MikeTheWatchGuy** [comment] 2018-09-29 05:50
OH WOW!!!!!!!!!!!!!!!!!!!

**Comment by eagleEggs** [comment] 2018-09-29 06:02
No problem. I was on the edge of making this a console app but PySimpleGUI saved that and will make it much easier for non technical users to use it in the future! I was not going to touch tkinter as I didn't want to invest that much time in learning that library - It's great - But requires MUCH more tuning and code.

But which readme are you talking about? I checked and don't see anything.

**Comment by eagleEggs** [comment] 2018-09-29 06:31
LOL I'm so tired.... I can't even. Literally started laughing before I found it because I kept reading up and down and didn't see anything and it was just silly. And then I found it... That's hilarious!

But yes, without a GUI... the plan was to basically have testers literally execute the script after editing/ sysargs on CLI / or pull configs from a file would be a mess. A MESS! Especially for people who don't really mess with code at all.

**Comment by MikeTheWatchGuy** [comment] 2018-09-29 06:51
Oh wow... I can't imagine doing all that without a GUI!

 # A MESS

You've gone from that to a COOL looking GUI... your testers are doing to LOVE YOU!

**Comment by eagleEggs** [comment] 2018-09-29 06:54
We will see haha. This should cover a lot of the normal workload (regression) and let them focus on finding other bugs.

**Comment by eagleEggs** [comment] 2018-09-30 02:37
Having conceptual issues with updating tab contents with updating screenshot images. I can do it at start, but want it to refresh mid app use. The variables are all over the place and not sure yet how the GUI can handle updates with where the variables are located. Basically the same setup as your Demo_Img_Viewer.py but modifying it to have a button to refresh the image list.

I've tried a few setups by recalling functions and such instead of having it only parsing existing files once but it's always the case of chasing down variables in an endless loop :/

One main issue is the placement of:

`col = [[filename_display_elem],
          [image_elem]]

`

Which when building out functions, these are always not available from the layouts.

If you have some insight that would be great!

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 02:40
I can't debug a complex GUI issue from a couple paragraphs of text.  I know it's not easy but you have to send a screen shot and some sample code would be best.

I don't know where to start answering when you say something like:
>The variables are all over the place 

What does that mean?  Does that mean my interfaces suck or your code sucks?

**Comment by eagleEggs** [comment] 2018-09-30 02:44
Let me spend a bit more time on it. I think mainly I'm assuming a lot of things with the GUI code and where it 'needs' to be. I think I'm wrong about a lot of it :P Thanks

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 02:45
There was also a recent change to keys and listboxes.  I see the image browser has broken as a result.  It could be these last sets of changes busted stuff

**Comment by eagleEggs** [comment] 2018-09-30 02:53
I worked around that by pulling the expected folder from my class, so that wasn't a big deal. But that had to do with the GetPathBox that was missing.

**Comment by eagleEggs** [comment] 2018-09-30 03:02
Is it possible to do something like this?:

`col5 =  [[sg.ReadButton("Generate")],[sg.T("")],
'        for imagery in fnames:
'        	[image_elem]]`

To iterate over loop results that will vary? Or perhaps an easier way to expand a list within a column?

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 03:05
Maybe it's the drugs, but I don't understand either of the past 2 messages.

**Comment by eagleEggs** [comment] 2018-09-30 03:06
That's probably because I'm likely reinventing the wheel for something that is already built in and don't realize it lol

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 03:09
Don't do that! I do plenty of that for you!  I'm great at the wheel..

**Comment by eagleEggs** [comment] 2018-09-30 03:13
Well I can put an image on the canvas, that's fine. But I'm trying to loop through all images and display them on the canvas next to each other. The problem is, it seems I can't update the col in realtime to accommodate the total number of files:

https://gist.github.com/eagleEggs/3cda3c0000fcdc474124f0ae7adbce46

So, I'd like to duplicate the [image_elem]] within the column - Unless there is some built in way to manage it.

**Comment by eagleEggs** [comment] 2018-09-30 03:28
Got it. I knew it was easier than I was thinking...

https://gist.github.com/eagleEggs/3cda3c0000fcdc474124f0ae7adbce46#gistcomment-2720030

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 03:35
There you go...

Don't try and get clever right from the start.

I start with the long form answer to my problems.  I don't start thinking that I'm going to create a 1-line solution with an iterator.  I start with a for loop and perhaps an append.   AFTER I get that WORKING, then I start to work compacting it.  

I've not done this until I started with Python.  I'll look at a 4 or 5 line block of code that does something as if it's a puzzle.  It's like a mini-Sudoku puzzle.

**Comment by eagleEggs** [comment] 2018-09-30 03:38
True. Also as you mentioned before - Remembering that most of what you're making are lists and dictionaries helps, which was my moment to make this less complicated.

**Comment by eagleEggs** [comment] 2018-09-30 04:47
Is there actually a way to update a column with a new list at runtime and then refresh window?

`col5 =  [[sg.ReadButton("Generate Screenshots")]]`

`if b is "Generate Screenshots":

    	folder = instantiate_app.folder
    	print(folder)
    	flist0 = os.listdir(folder)
    	fnames = [f for f in flist0 if os.path.isfile(os.path.join(folder,f)) and f.lower().endswith(".png")]
    	num_files = len(fnames)
    	print(num_files)
    	if num_files == 0:
    		print("passing")
    		pass

    	del flist0
    	del image_elem
    	image_elem = []
    	image_elem.append([sg.Button("Generate Screenshots")])
    	image_elem.append([sg.T("")])
    	for image in fnames:
    		filename = os.path.join(folder, image)  # name of first file in list
    		image_elem.append([sg.Image(data = get_img_data(filename, first = True))])

    	#col5 =  image_elem
    	window.FindElement('screenshots').AddRow(image_elem)`

I've tried many things besides this as well.

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 04:50
What do you mean by "update a column"?

There is no Update method on a column.

Do you mean add more elements to a Window?  The answer to that one is no, Windows cannot be dynamically grown nor shrank.

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 04:51
Once you call Finalize or Read, you're done with that Window's elements.  You can no longer add nor subtract.  Thus the word Finalize ;-)

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 04:52
Maybe if you could describe what you are trying to do I could better help.  Hearing snippets of things you've tried and failed with doesn't get me far into understanding the desired outcome.

**Comment by eagleEggs** [comment] 2018-09-30 04:53
Aaah ok... So it seems I may not be able to dynamically regenerate images on the GUI with images that are added to a folder after the fact?

That's actually fine. I am just going to pop up a new window which will grab the new values.

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 04:53
It's a popular request.... "dynamic forms" and one I've tried to be clear about so people don't waste their time trying.

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 04:55
The only way I can think of if you want to dynamically grow a window is to create an entirely new window and show that.

**Comment by eagleEggs** [comment] 2018-09-30 04:55
Yep that's what I did :D Thanks

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 04:56
Add your layout inside of your loop... do not try to re-use a layout.. I logged an issue about that to warn people.

**Comment by eagleEggs** [comment] 2018-09-30 05:04
This way works really well. Great!

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 05:07
Whew!

Really?!  Works great?

I keep thinking you have hit a roadblock that has stopped your project entirely.

**Comment by eagleEggs** [comment] 2018-09-30 05:15
No, no :) There's always a workaround.

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 06:12
My biggest fear, partly because I was beaten up over this when I first posted about the package, is that someone will start coding up their stuff and then get 80% of the way there only do discover there's a missing feature or that a feature doesn't work the way stated thus,their project was a waste of time.

I had a ton of people voice these kinds of concerns.  A lot of them seemed to be looking for reasons they could not use it, in a nebulous kind of way.

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 06:15
Screenshots!

Wait, what's 12?  That looks like a browser or some other scrolled object. I don't do scrolling very well at all.

**Comment by eagleEggs** [comment] 2018-09-30 06:29
Right now, the testers test regression manually. This will automate it. There isn't currently any automation. My original plan before using PSG was to build it as console. But with the GUI, a lot of neat functionality becomes available.

But overall, most testing automation isnt built on GUI's. They are ran as scripts and then just basic reporting is done. The Selenium API is the most famous. And adding a GUI is completely optional and usually not done. But giving a user a GUI and not having to train how to use console and such makes it much more accessible.

**Comment by eagleEggs** [comment] 2018-09-30 06:30
Implementing automation will take what usually takes weeks into less than a day :/ !!! woohoo

**Comment by MikeTheWatchGuy** [comment] 2018-09-30 06:33
It’s really hard to argue that typing a command into a terminal window is quicker than a button push…. Although some people will make that argument.

**Comment by eagleEggs** [comment] 2018-09-30 06:36
For technical users that's fine. But giving a console app to users who can't do ipconfig is a challenge.

**Comment by eagleEggs** [comment] 2018-09-30 14:50
Going to close this out.

**Closed by eagleEggs** 2018-09-30 14:50 UTC
